-- MCA Mail core schema.
--
-- Design notes
--   * All primary keys are UUIDv4 generated by the application, so identifiers
--     stay stable across mailbox migrations and provider changes.
--   * Provider-side keys (IMAP UID + UIDVALIDITY, RFC 5322 Message-ID) live in
--     dedicated columns with unique indexes; they are the dedup mechanism.
--   * Enumerations are stored as TEXT with CHECK constraints rather than native
--     enum types, so adding a value is an ordinary migration and an unknown
--     legacy value surfaces as a parse error instead of a broken query.
--   * Every timestamp is `timestamptz` and stored in UTC.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- threads and emails
-- ---------------------------------------------------------------------------

CREATE TABLE email_threads (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    root_message_id     TEXT,
    normalized_subject  TEXT        NOT NULL,
    conversation_key    TEXT        NOT NULL UNIQUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_email_threads_root ON email_threads (root_message_id);

CREATE TABLE emails (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id               UUID        NOT NULL REFERENCES email_threads (id) ON DELETE CASCADE,
    direction               TEXT        NOT NULL CHECK (direction IN ('inbound', 'outbound')),
    status                  TEXT        NOT NULL CHECK (status IN
                                ('pending', 'processing', 'processed', 'quarantined',
                                 'needs_review', 'failed', 'dead')),
    category                TEXT        CHECK (category IS NULL OR category IN
                                ('new_lead', 'existing_client', 'partner', 'transport_request',
                                 'full_import_request', 'customs_request', 'procurement_request',
                                 'document_request', 'complaint', 'internal', 'advertisement',
                                 'spam', 'uncertain')),
    spam_verdict            TEXT        CHECK (spam_verdict IS NULL OR spam_verdict IN
                                ('spam', 'advertisement', 'phishing_suspected',
                                 'automated_notification', 'not_spam', 'uncertain')),
    mailbox_action          TEXT        NOT NULL DEFAULT 'none' CHECK (mailbox_action IN
                                ('none', 'move_to_inbox', 'move_to_quarantine', 'add_label',
                                 'mark_read', 'archive')),
    provider                TEXT        NOT NULL,
    mailbox                 TEXT        NOT NULL,
    provider_uid            TEXT,
    provider_uid_validity   BIGINT,
    internet_message_id     TEXT,
    in_reply_to             TEXT,
    -- `references` is a reserved SQL keyword, so the RFC 5322 header column is
    -- always double-quoted in queries. The Rust field stays `references`.
    "references"            TEXT[]      NOT NULL DEFAULT '{}',
    from_address            TEXT        NOT NULL,
    from_name               TEXT,
    to_addresses            TEXT[]      NOT NULL DEFAULT '{}',
    cc_addresses            TEXT[]      NOT NULL DEFAULT '{}',
    subject                 TEXT        NOT NULL,
    normalized_subject      TEXT        NOT NULL,
    date                    TIMESTAMPTZ,
    received_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    text_body               TEXT        NOT NULL DEFAULT '',
    html_present            BOOLEAN     NOT NULL DEFAULT FALSE,
    size_bytes              BIGINT      NOT NULL DEFAULT 0,
    lead_id                 UUID,
    labels                  TEXT[]      NOT NULL DEFAULT '{}',
    dedup_key               TEXT        NOT NULL,
    attempts                INT         NOT NULL DEFAULT 0,
    last_error              TEXT,
    processed_at            TIMESTAMPTZ,
    anonymized_at           TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Provider identity: the strongest dedup signal available.
CREATE UNIQUE INDEX uq_emails_provider_uid
    ON emails (mailbox, provider_uid, provider_uid_validity)
    WHERE provider_uid IS NOT NULL;

CREATE UNIQUE INDEX uq_emails_dedup_key ON emails (dedup_key);
CREATE UNIQUE INDEX uq_emails_internet_message_id
    ON emails (mailbox, internet_message_id)
    WHERE internet_message_id IS NOT NULL;

CREATE INDEX idx_emails_status ON emails (status, received_at DESC);
CREATE INDEX idx_emails_thread ON emails (thread_id, received_at);
CREATE INDEX idx_emails_from ON emails (from_address, received_at DESC);
CREATE INDEX idx_emails_lead ON emails (lead_id) WHERE lead_id IS NOT NULL;
CREATE INDEX idx_emails_received ON emails (received_at DESC);
CREATE INDEX idx_emails_in_reply_to ON emails (in_reply_to) WHERE in_reply_to IS NOT NULL;

-- ---------------------------------------------------------------------------
-- attachments and labels
-- ---------------------------------------------------------------------------

CREATE TABLE email_attachments (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email_id        UUID        NOT NULL REFERENCES emails (id) ON DELETE CASCADE,
    filename        TEXT        NOT NULL,
    mime_type       TEXT        NOT NULL,
    size_bytes      BIGINT      NOT NULL,
    content_id      TEXT,
    is_inline       BOOLEAN     NOT NULL DEFAULT FALSE,
    sha256          TEXT        NOT NULL,
    extraction      TEXT        NOT NULL,
    extracted_chars INT         NOT NULL DEFAULT 0,
    text_excerpt    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_attachments_email ON email_attachments (email_id);
CREATE INDEX idx_attachments_sha ON email_attachments (sha256);

CREATE TABLE email_labels (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mailbox     TEXT        NOT NULL,
    name        TEXT        NOT NULL,
    color       TEXT,
    is_system   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (mailbox, name)
);

CREATE TABLE email_label_assignments (
    email_id    UUID        NOT NULL REFERENCES emails (id) ON DELETE CASCADE,
    label_id    UUID        NOT NULL REFERENCES email_labels (id) ON DELETE CASCADE,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (email_id, label_id)
);

-- ---------------------------------------------------------------------------
-- leads
-- ---------------------------------------------------------------------------

CREATE TABLE leads (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id                UUID        REFERENCES email_threads (id) ON DELETE SET NULL,
    primary_email_id         UUID        REFERENCES emails (id) ON DELETE SET NULL,
    source                   TEXT        NOT NULL CHECK (source IN ('inbound_email', 'api', 'manager')),
    status                   TEXT        NOT NULL CHECK (status IN
                                ('new', 'processing', 'awaiting_customer', 'qualified',
                                 'needs_human_review', 'handed_off', 'in_progress', 'won',
                                 'lost', 'closed')),
    category                 TEXT,
    scope                    TEXT        NOT NULL CHECK (scope IN
                                ('transport', 'customs', 'procurement', 'full_import')),
    conversation_key         TEXT        NOT NULL UNIQUE,
    contact_email            TEXT        NOT NULL,
    company_name             TEXT,
    company_inn              TEXT,
    summary                  TEXT,
    confidence               REAL,
    open_questions           JSONB       NOT NULL DEFAULT '[]'::jsonb,
    unresolved_topics        JSONB       NOT NULL DEFAULT '[]'::jsonb,
    callback_requested       BOOLEAN     NOT NULL DEFAULT FALSE,
    callback_phone           TEXT,
    automation_released_by   UUID,
    automation_locked        BOOLEAN     NOT NULL DEFAULT FALSE,
    last_activity_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_leads_status ON leads (status, last_activity_at DESC);
CREATE INDEX idx_leads_email ON leads (contact_email);
CREATE INDEX idx_leads_inn ON leads (company_inn) WHERE company_inn IS NOT NULL;
CREATE INDEX idx_leads_thread ON leads (thread_id) WHERE thread_id IS NOT NULL;
CREATE INDEX idx_leads_callback ON leads (callback_requested)
    WHERE callback_requested = TRUE;

ALTER TABLE emails
    ADD CONSTRAINT fk_emails_lead FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE SET NULL;

CREATE TABLE lead_contacts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id         UUID        NOT NULL REFERENCES leads (id) ON DELETE CASCADE,
    name            TEXT,
    position        TEXT,
    email           TEXT,
    phone           TEXT,
    telegram        TEXT,
    company_name    TEXT,
    company_inn     TEXT,
    is_primary      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_lead_contacts_primary_email
    ON lead_contacts (lead_id, email) WHERE email IS NOT NULL;
CREATE INDEX idx_lead_contacts_lead ON lead_contacts (lead_id);

-- Per-field commercial requirements with explicit knowledge state.
CREATE TABLE lead_requirements (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id     UUID        NOT NULL REFERENCES leads (id) ON DELETE CASCADE,
    field       TEXT        NOT NULL,
    value       TEXT,
    state       TEXT        NOT NULL CHECK (state IN
                    ('known', 'unknown', 'not_applicable', 'needs_confirmation')),
    source      TEXT        NOT NULL CHECK (source IN ('customer', 'ai_inference', 'manager')),
    unit        TEXT,
    confidence  REAL,
    evidence    TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (lead_id, field)
);

CREATE INDEX idx_requirements_state ON lead_requirements (lead_id, state);
CREATE INDEX idx_requirements_incomplete
    ON lead_requirements (lead_id) WHERE state <> 'known';

CREATE TABLE lead_conversations (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id          UUID        NOT NULL REFERENCES leads (id) ON DELETE CASCADE,
    email_id         UUID        REFERENCES emails (id) ON DELETE SET NULL,
    direction        TEXT        NOT NULL CHECK (direction IN ('inbound', 'outbound')),
    state            TEXT        NOT NULL CHECK (state IN
                        ('draft', 'approved', 'sent', 'rejected', 'suppressed')),
    subject          TEXT        NOT NULL,
    body             TEXT        NOT NULL,
    idempotency_key  TEXT        NOT NULL UNIQUE,
    sent_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_conversations_lead ON lead_conversations (lead_id, created_at DESC);
CREATE INDEX idx_conversations_email ON lead_conversations (email_id) WHERE email_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- company research
-- ---------------------------------------------------------------------------

CREATE TABLE company_research (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id         UUID        REFERENCES leads (id) ON DELETE CASCADE,
    identifier      TEXT        NOT NULL,
    status          TEXT        NOT NULL CHECK (status IN
                        ('not_configured', 'pending', 'completed', 'partial', 'failed',
                         'no_identifier')),
    inn             TEXT,
    ogrn            TEXT,
    legal_name      TEXT,
    company_state   TEXT,
    registered_at   TIMESTAMPTZ,
    region          TEXT,
    main_activity   TEXT,
    management      TEXT,
    liquidation_signs BOOLEAN,
    court_cases     INT,
    enforcement_cases INT,
    revenue_last_year DOUBLE PRECISION,
    profit_last_year  DOUBLE PRECISION,
    completeness    REAL        NOT NULL DEFAULT 0,
    sources         JSONB       NOT NULL DEFAULT '[]'::jsonb,
    gaps            JSONB       NOT NULL DEFAULT '[]'::jsonb,
    flags           JSONB       NOT NULL DEFAULT '[]'::jsonb,
    notes           TEXT,
    performed_at    TIMESTAMPTZ,
    expires_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One live report per identifier; stale rows are replaced, not accumulated.
CREATE UNIQUE INDEX uq_company_research_identifier
    ON company_research (identifier, COALESCE(lead_id, '00000000-0000-0000-0000-000000000000'));
CREATE INDEX idx_company_research_lead ON company_research (lead_id) WHERE lead_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- processing runs, agent runs, tool calls, events
-- ---------------------------------------------------------------------------

CREATE TABLE email_processing_runs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email_id            UUID        NOT NULL REFERENCES emails (id) ON DELETE CASCADE,
    thread_id           UUID        NOT NULL REFERENCES email_threads (id) ON DELETE CASCADE,
    lead_id             UUID        REFERENCES leads (id) ON DELETE SET NULL,
    state               TEXT        NOT NULL CHECK (state IN
                            ('queued', 'running', 'succeeded', 'failed', 'cancelled',
                             'retry_scheduled')),
    trigger             TEXT        NOT NULL CHECK (trigger IN ('poll', 'manual', 'api', 'retry')),
    attempt             INT         NOT NULL DEFAULT 1,
    current_stage       TEXT,
    stages_completed    TEXT[]      NOT NULL DEFAULT '{}',
    error               TEXT,
    total_tokens        BIGINT      NOT NULL DEFAULT 0,
    cost_micros_usd     BIGINT      NOT NULL DEFAULT 0,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_runs_email ON email_processing_runs (email_id, started_at DESC);
CREATE INDEX idx_runs_state ON email_processing_runs (state, started_at);
CREATE INDEX idx_runs_lead ON email_processing_runs (lead_id) WHERE lead_id IS NOT NULL;
-- At most one live run per email: guards against double processing.
CREATE UNIQUE INDEX uq_runs_active_email
    ON email_processing_runs (email_id)
    WHERE state IN ('queued', 'running', 'retry_scheduled');

CREATE TABLE agent_runs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id              UUID        NOT NULL REFERENCES email_processing_runs (id) ON DELETE CASCADE,
    email_id            UUID        NOT NULL REFERENCES emails (id) ON DELETE CASCADE,
    agent               TEXT        NOT NULL,
    model               TEXT        NOT NULL DEFAULT '',
    tier                TEXT        NOT NULL DEFAULT 'standard',
    state               TEXT        NOT NULL CHECK (state IN
                            ('queued', 'running', 'succeeded', 'failed', 'cancelled',
                             'retry_scheduled')),
    iterations          INT         NOT NULL DEFAULT 0,
    tool_calls          INT         NOT NULL DEFAULT 0,
    prompt_tokens       BIGINT      NOT NULL DEFAULT 0,
    completion_tokens   BIGINT      NOT NULL DEFAULT 0,
    cost_micros_usd     BIGINT      NOT NULL DEFAULT 0,
    duration_ms         BIGINT      NOT NULL DEFAULT 0,
    error               TEXT,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at         TIMESTAMPTZ
);

CREATE INDEX idx_agent_runs_run ON agent_runs (run_id, started_at);
CREATE INDEX idx_agent_runs_agent ON agent_runs (agent, started_at DESC);

CREATE TABLE tool_calls (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id          UUID        NOT NULL REFERENCES email_processing_runs (id) ON DELETE CASCADE,
    agent_run_id    UUID        NOT NULL REFERENCES agent_runs (id) ON DELETE CASCADE,
    email_id        UUID        NOT NULL REFERENCES emails (id) ON DELETE CASCADE,
    agent           TEXT        NOT NULL,
    tool_name       TEXT        NOT NULL,
    arguments       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    status          TEXT        NOT NULL CHECK (status IN
                        ('started', 'succeeded', 'failed', 'denied', 'timed_out')),
    result_preview  TEXT,
    error           TEXT,
    duration_ms     BIGINT      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_tool_calls_run ON tool_calls (run_id, created_at);
CREATE INDEX idx_tool_calls_tool ON tool_calls (tool_name, created_at DESC);

CREATE TABLE processing_events (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id      UUID        REFERENCES email_processing_runs (id) ON DELETE CASCADE,
    email_id    UUID        REFERENCES emails (id) ON DELETE CASCADE,
    lead_id     UUID        REFERENCES leads (id) ON DELETE CASCADE,
    stage       TEXT,
    severity    TEXT        NOT NULL CHECK (severity IN ('debug', 'info', 'warning', 'error')),
    code        TEXT        NOT NULL,
    message     TEXT        NOT NULL,
    details     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_events_run ON processing_events (run_id, created_at);
CREATE INDEX idx_events_email ON processing_events (email_id, created_at DESC);
CREATE INDEX idx_events_lead ON processing_events (lead_id, created_at DESC) WHERE lead_id IS NOT NULL;
CREATE INDEX idx_events_created ON processing_events (created_at DESC);

-- ---------------------------------------------------------------------------
-- drafts and handoffs
-- ---------------------------------------------------------------------------

CREATE TABLE email_drafts (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id             UUID        REFERENCES leads (id) ON DELETE CASCADE,
    email_id            UUID        REFERENCES emails (id) ON DELETE SET NULL,
    run_id              UUID        REFERENCES email_processing_runs (id) ON DELETE SET NULL,
    in_reply_to         TEXT,
    to_addresses        TEXT[]      NOT NULL DEFAULT '{}',
    cc_addresses        TEXT[]      NOT NULL DEFAULT '{}',
    subject             TEXT        NOT NULL,
    body                TEXT        NOT NULL,
    status              TEXT        NOT NULL CHECK (status IN
                            ('pending_approval', 'approved', 'rejected', 'sent', 'suppressed')),
    idempotency_key     TEXT        NOT NULL UNIQUE,
    suppression_reason  TEXT,
    reviewed_by         TEXT,
    reviewed_at         TIMESTAMPTZ,
    sent_at             TIMESTAMPTZ,
    provider_message_id TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_drafts_status ON email_drafts (status, created_at DESC);
CREATE INDEX idx_drafts_lead ON email_drafts (lead_id) WHERE lead_id IS NOT NULL;
-- At most one live draft per lead, so reprocessing cannot queue a second reply.
CREATE UNIQUE INDEX uq_drafts_live_per_lead
    ON email_drafts (lead_id) WHERE lead_id IS NOT NULL AND status IN ('pending_approval', 'approved');

CREATE TABLE human_handoffs (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id              UUID        NOT NULL REFERENCES leads (id) ON DELETE CASCADE,
    thread_id            UUID        REFERENCES email_threads (id) ON DELETE SET NULL,
    run_id               UUID        REFERENCES email_processing_runs (id) ON DELETE SET NULL,
    email_id             UUID        REFERENCES emails (id) ON DELETE SET NULL,
    reason               TEXT        NOT NULL,
    priority             INT         NOT NULL DEFAULT 20,
    state                TEXT        NOT NULL CHECK (state IN
                             ('open', 'acknowledged', 'resolved', 'returned_to_automation')),
    contact_email        TEXT        NOT NULL,
    contact_name         TEXT,
    contact_phone        TEXT,
    company_name         TEXT,
    company_inn          TEXT,
    original_request     TEXT        NOT NULL DEFAULT '',
    category             TEXT,
    spam_verdict         TEXT,
    cargo_summary        TEXT        NOT NULL DEFAULT '',
    route_summary        TEXT        NOT NULL DEFAULT '',
    requested_service    TEXT        NOT NULL DEFAULT '',
    missing_information  JSONB       NOT NULL DEFAULT '[]'::jsonb,
    open_questions       JSONB       NOT NULL DEFAULT '[]'::jsonb,
    conversation_digest  TEXT        NOT NULL DEFAULT '',
    research_digest      TEXT,
    checks_performed     JSONB       NOT NULL DEFAULT '[]'::jsonb,
    unresolved_topics    JSONB       NOT NULL DEFAULT '[]'::jsonb,
    assigned_to          TEXT,
    acknowledged_at      TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_handoffs_state ON human_handoffs (state, priority DESC, created_at);
CREATE INDEX idx_handoffs_lead ON human_handoffs (lead_id, created_at DESC);
-- One open handoff per lead: repeated escalation updates the existing one.
CREATE UNIQUE INDEX uq_handoffs_open_per_lead
    ON human_handoffs (lead_id) WHERE state IN ('open', 'acknowledged');

-- ---------------------------------------------------------------------------
-- audit, settings, operators
-- ---------------------------------------------------------------------------

CREATE TABLE audit_logs (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor         TEXT        NOT NULL,
    actor_role    TEXT        NOT NULL,
    action        TEXT        NOT NULL,
    resource_type TEXT        NOT NULL,
    resource_id   TEXT,
    outcome       TEXT        NOT NULL CHECK (outcome IN ('success', 'denied', 'failure')),
    details       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    request_id    TEXT,
    remote_addr   TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_created ON audit_logs (created_at DESC);
CREATE INDEX idx_audit_actor ON audit_logs (actor, created_at DESC);
CREATE INDEX idx_audit_resource ON audit_logs (resource_type, resource_id);

CREATE TABLE system_settings (
    key         TEXT PRIMARY KEY,
    value       JSONB       NOT NULL,
    description TEXT,
    updated_by  TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE api_keys (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          TEXT        NOT NULL,
    role          TEXT        NOT NULL CHECK (role IN ('admin', 'manager', 'operator', 'viewer')),
    key_hash      TEXT        NOT NULL UNIQUE,
    prefix        TEXT        NOT NULL,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    last_used_at  TIMESTAMPTZ,
    expires_at    TIMESTAMPTZ,
    created_by    TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_api_keys_prefix ON api_keys (prefix);

-- ---------------------------------------------------------------------------
-- outbox: mailbox mutations requested while the gateway was offline or the
-- mode forbade applying them. Applied by a worker once policy allows.
-- ---------------------------------------------------------------------------

CREATE TABLE mailbox_outbox (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email_id     UUID        NOT NULL REFERENCES emails (id) ON DELETE CASCADE,
    action       TEXT        NOT NULL CHECK (action IN
                    ('move', 'label', 'mark_read', 'archive', 'flag')),
    target       TEXT,
    applied      BOOLEAN     NOT NULL DEFAULT FALSE,
    attempts     INT         NOT NULL DEFAULT 0,
    last_error   TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    applied_at   TIMESTAMPTZ
);

CREATE INDEX idx_outbox_pending ON mailbox_outbox (created_at) WHERE applied = FALSE;

-- ---------------------------------------------------------------------------
-- helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_emails_updated BEFORE UPDATE ON emails
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_threads_updated BEFORE UPDATE ON email_threads
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_leads_updated BEFORE UPDATE ON leads
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
